# Generated by Django 6.0.3 on 2026-04-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255)),
                ('rate_type', models.CharField(max_length=100)),
                ('rate_value', models.FloatField()),
                ('effective_date', models.DateField()),
                ('ingestion_ts', models.DateTimeField()),
                ('source_url', models.URLField()),
                ('raw_response_id', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('provider', 'rate_type', 'effective_date', 'raw_response_id')},
            },
        ),
    ]
